---
name: Go release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'
      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y upx
          make dev-dependencies
          make release
          find build -type f ! -name "*.md5" ! -name "*.sha256" -exec upx -9 {} \;
      - uses: softprops/action-gh-release@v1
        with:
          files: "build/kafka-offset-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish to docker hub
        run: |
          make docker
          make docker-deploy
